#!/usr/bin/env python3
"""Prepare an isolated Forge GameTest run containing only failed tests.

Forge's development GameTest runner has no reliable test-name filter.  This
tool keeps the normal source tree untouched: it copies the GameTest package to
``build/selected-gametests`` and removes only unselected ``@GameTest``
annotations in that copy.  The generated Gradle init script compiles the copy
plus every non-GameTest production package into
``build/selected-gametest-classes`` for one ``runGameTestServer`` invocation.

Use ``--prepare-only`` to inspect the selection before starting Minecraft.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path


FAILURE_HEADER = re.compile(r"\b\d+ required tests failed\b", re.IGNORECASE)
FAILURE_NAME = re.compile(r"\s-\s+([a-z0-9_]+)\s*$", re.IGNORECASE)
GAME_TEST = re.compile(r"@GameTest\b")
METHOD = re.compile(r"\bpublic\s+static\s+void\s+(\w+)\s*\(")


def failed_names(log: Path) -> list[str]:
    """Return the final failure list in a GameTest server log."""
    lines = log.read_text(encoding="utf-8", errors="replace").splitlines()
    starts = [index for index, line in enumerate(lines) if FAILURE_HEADER.search(line)]
    if not starts:
        raise ValueError(f"No required-test failure summary found in {log}")
    result: list[str] = []
    for line in lines[starts[-1] + 1:]:
        match = FAILURE_NAME.search(line)
        if match:
            result.append(match.group(1).lower())
            continue
        if result:
            break
    if not result:
        raise ValueError(f"Failure summary in {log} did not contain test names")
    return list(dict.fromkeys(result))


def annotation_end(source: str, start: int) -> int:
    """Find the end of one @GameTest annotation, including arguments."""
    cursor = start + len("@GameTest")
    while cursor < len(source) and source[cursor].isspace() and source[cursor] != "\n":
        cursor += 1
    if cursor >= len(source) or source[cursor] != "(":
        return cursor
    depth = 0
    in_string = False
    escaped = False
    while cursor < len(source):
        char = source[cursor]
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
        elif char == '"':
            in_string = True
        elif char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return cursor + 1
        cursor += 1
    raise ValueError("Unterminated @GameTest annotation")


def disable_unselected_annotations(path: Path, selected: set[str]) -> tuple[set[str], int]:
    """Blank annotations for unselected methods while preserving source lines."""
    source = path.read_text(encoding="utf-8")
    replacements: list[tuple[int, int]] = []
    found: set[str] = set()
    enabled = 0
    for match in GAME_TEST.finditer(source):
        start = match.start()
        end = annotation_end(source, start)
        method_match = METHOD.search(source, end)
        if method_match is None:
            raise ValueError(f"No public static GameTest method after annotation in {path}")
        method = method_match.group(1)
        name = method.lower()
        if name in selected:
            found.add(name)
            enabled += 1
        else:
            # Keep every newline so compiler diagnostics retain original line numbers.
            replacements.append((start, end))
    for start, end in reversed(replacements):
        source = source[:start] + "".join("\n" if char == "\n" else " " for char in source[start:end]) + source[end:]
    path.write_text(source, encoding="utf-8", newline="")
    return found, enabled


def annotated_test_names(path: Path) -> set[str]:
    """Read test method names without modifying the source file."""
    source = path.read_text(encoding="utf-8")
    names: set[str] = set()
    for match in GAME_TEST.finditer(source):
        method_match = METHOD.search(source, annotation_end(source, match.start()))
        if method_match is None:
            raise ValueError(f"No public static GameTest method after annotation in {path}")
        names.add(method_match.group(1).lower())
    return names


def groovy_path(path: Path) -> str:
    return path.resolve().as_posix().replace("'", "\\'")


def write_init_script(root: Path, selected_root: Path, init_path: Path) -> None:
    init_path.write_text(
        f"""// Generated by tools/run_gametest_failures.py. Do not commit.
def selectedGameTests = new File('{groovy_path(selected_root)}')
gradle.projectsLoaded {{
    def p = gradle.rootProject
    gradle.projectsEvaluated {{
        def selectedCompile = p.tasks.named('compileJava', JavaCompile)
        selectedCompile.configure {{
            setSource(p.files(
                p.fileTree('src/main/java') {{
                    include '**/*.java'
                    exclude 'com/yu1745/chemicaladdon/gametest/**'
                }},
                p.fileTree(selectedGameTests) {{ include '**/*.java' }}
            ))
            destinationDirectory.set(p.layout.buildDirectory.dir('selected-gametest-classes'))
        }}
        p.sourceSets.main.output.classesDirs.setFrom(selectedCompile.flatMap {{ it.destinationDirectory }})
    }}
}}
""",
        encoding="utf-8",
        newline="\n",
    )


def prepare(root: Path, log: Path, include: list[str]) -> tuple[Path, Path, list[str]]:
    selected = failed_names(log) + include
    duplicate_names = sorted({name for name in selected if selected.count(name) > 1})
    if duplicate_names:
        raise ValueError("Duplicate selected GameTest names: " + ", ".join(duplicate_names))
    source_root = root / "src" / "main" / "java" / "com" / "yu1745" / "chemicaladdon" / "gametest"
    output_root = root / "build" / "selected-gametests"
    copied_package = output_root / "com" / "yu1745" / "chemicaladdon" / "gametest"
    if not source_root.is_dir():
        raise ValueError(f"GameTest source directory does not exist: {source_root}")
    available = set().union(*(annotated_test_names(path) for path in source_root.rglob("*.java")))
    missing = sorted(set(selected) - available)
    if missing:
        raise ValueError("Failed test names not found as @GameTest methods: " + ", ".join(missing))
    build_root = (root / "build").resolve()
    resolved_output = output_root.resolve()
    try:
        within_build = os.path.commonpath((str(build_root), str(resolved_output))) == str(build_root)
    except ValueError:
        within_build = False
    if output_root.is_symlink() or resolved_output == build_root or not within_build:
        raise ValueError(f"Refusing to delete selected output outside build directory: {output_root}")
    shutil.rmtree(output_root, ignore_errors=True)
    copied_package.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(source_root, copied_package)
    selected_set = set(selected)
    found: set[str] = set()
    enabled = 0
    for path in copied_package.rglob("*.java"):
        current_found, current_enabled = disable_unselected_annotations(path, selected_set)
        found.update(current_found)
        enabled += current_enabled
    missing = sorted(selected_set - found)
    if missing:
        raise AssertionError("Selected test disappeared while copying: " + ", ".join(missing))
    manifest = {
        "source_log": str(log.resolve()),
        "selected_count": len(selected),
        "enabled_annotation_count": enabled,
        "selected_tests": selected,
        "classes_output": str((root / "build" / "selected-gametest-classes").resolve()),
    }
    (output_root / "selection.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    init_path = output_root / "selected-gametests.init.gradle"
    write_init_script(root, output_root, init_path)
    return output_root, init_path, selected


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--log", type=Path, default=Path("build/native-gametest.log"),
                        help="GameTest server log containing the final failure summary")
    parser.add_argument("--prepare-only", action="store_true",
                        help="Generate the isolated source/init script but do not invoke Gradle")
    parser.add_argument("--include", default="",
                        help="Comma-separated additional GameTest method names to retain")
    parser.add_argument("--gradle", default="gradlew.bat" if sys.platform == "win32" else "./gradlew",
                        help="Gradle launcher used when --prepare-only is omitted")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    log = args.log if args.log.is_absolute() else root / args.log
    try:
        include = [name.strip().lower() for name in args.include.split(",") if name.strip()]
        output_root, init_path, selected = prepare(root, log, include)
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    command = [args.gradle, "--init-script", str(init_path), "runGameTestServer"]
    print(f"Prepared {len(selected)} selected GameTests in {output_root}")
    print(f"Init script: {init_path}")
    print("Selected:", ", ".join(selected))
    print("Run:", " ".join(command))
    if args.prepare_only:
        return 0
    return subprocess.run(command, cwd=root).returncode


if __name__ == "__main__":
    raise SystemExit(main())
